[package]
name = "Rusty-Chest"
version = "0.1.0"
authors = ["Jason Hall <jason@mahletconsulting.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
